### PR TITLE
Refactor(fivetran_sdk): Improvement destination examples

### PR DESCRIPTION
**Pull request by fivetran-abdulsalam**
Links: https://fivetran.height.app/T-718406

**Description of change**
* Added a missing field `VisibilityCondition`
* Added example usage of `FieldSet`

**Testing done:**
* Python and Java examples are successful:
Screenshot 2024-06-24 at 5 35 25 PM
Screenshot 2024-06-24 at 5 36 31 PM

### CODE REVIEW

**Review by fivetran-niketkhandelwal — APPROVED** [review]
lgtm

**Comment by fivetran-abdulsalam** [comment]
@fivetran-satvikpatil `required` can be true. 
Assume a case where base on a radio button,  we want user to enter either enter password or the API secret Key. 
In both the conditions we will need `required` as `true`,

**Comment by fivetran-abdulsalam** [comment]
And in this case lets assume user selected private as false. The what if the ssh tunnel filed can be a mandatory field

**Comment by fivetran-satvikpatil** [comment]
> @fivetran-satvikpatil `required` can be true. Assume a case where base on a radio button, we want user to either enter password or the API secret Key. In both the conditions we will need `required` as `true` for password and Api key field

Ohhk, so if a customer provides a `password`, then as `api_key` is not provided, won't it cause any problem? I need to confirm how it is behaving in the setup form.

**Comment by fivetran-abdulsalam** [comment]
This is just and example where we are using `isPrivate` as visibility condition. 
Assume we have a setup form where we want user to enter the staging location(it can be S3, GCS or Azure storage creds).
And if we have a checkbox/radioButton base on the selection we want to show different creds fields and all of them could be mandatory.

**Review by fivetran-satvikpatil — APPROVED** [review]

**Pull request merged**
